name: Run Ray cluster

on:
  workflow_dispatch

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # GCP servica account authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Installing neccessary Ray plugins
      - name: Install Ray
        run: |
          pip install -U "ray[default]" google-api-python-client

      # Start Ray cluster defined in config
      - name: Start Ray cluster
        working-directory: ./ray
        run: |
          ray up -y configTest.yaml

      # Submit Ray model training job on the cluster
      - name: Submit Ray python job
        working-directory: ./ray
        run: |
          ray submit configTest.yaml test.py

      # Delete Ray cluster
      - name: Delete ray cluster
        working-directory: ./ray
        run: |
          ray down -y configTest.yaml
